### ISSUE TITLE
ショートカットをカスタマイズ

### ISSUE THREAD

**Issue by indigo-san** [b-editor/BEditor#220]
## 概要
ファンクションキーやジェスチャーで実行するコマンドをカスタマイズできるようにする

**Comment by yuto-trd** [comment]
## コマンド
* Ctrl+X - "カット"
* Ctrl+C - "コピー"
* Ctrl+V - "ペースト"
* Ctrl+O - "開く"
* Ctrl+Z - "Undo"
* Ctrl+Y - "Redo"
* Ctrl+N - "新規作成"
* Ctrl+S - "保存"
* Delete - "削除"
