### ISSUE TITLE
オブジェクトを選択するプロパティ

### ISSUE THREAD

**Issue by indigo-san** [b-editor/BEditor#251]
## 概要
* データツリーから指定した型のオブジェクトを検索する。
* 選択しているアイテムのIdを保存する
* Genericがついたバージョンも作る

**Comment by yuto-trd** [comment]
https://github.com/b-editor/BEditor/blob/main/src/BEditor.Primitive/Effects/Skia/Mask.cs#L206
この処理をすればいいだけなのでわざわざ新しく実装する必要なかった
