### ISSUE TITLE
Macでビルドがうまくいかない

### ISSUE THREAD

**Issue by Chipsnet** [b-editor/BEditor#285]
**バグの説明**
Macでビルドできない

エラーが表示される
```zsh
.NET 向け Microsoft (R) Build Engine バージョン 16.10.1+2fd48ab73
Copyright (C) Microsoft Corporation.All rights reserved.

  復元対象のプロジェクトを決定しています...
  /Users/minato86/Documents/Repository/BEditor/src/libraries/BEditor.Packaging/BEditor.Packaging.csproj を復元しました (310 ms)。
  /Users/minato86/Documents/Repository/BEditor/src/executable/BEditor.PackageInstaller/BEditor.PackageInstaller.csproj を復元しました (668 ms)。
/Users/minato86/Documents/Repository/BEditor/src/libraries/BEditor.Packaging/BEditor.Packaging.csproj(3,5): error MSB4019: インポートされたプロジェクト "/props/analyzer.props" が見つかりませんでした。Import 宣言 "/props/analyzer.props" の式が正しいことと、ファイルがディスク上に存在することを確認してください。
An error occurred when executing task 'AppPublish'.
Error: One or more errors occurred. (.NET Core CLI: Process returned an error (exit code 1).)
        .NET Core CLI: Process returned an error (exit code 1).
```

**再現**
再現するための手順:

1. dotnet 5.0 SDKをインストール
2. `dotnet restore`を実行
3. `dotnet cake`を実行
	1. `"dotnet tool restore" を実行して、"dotnet-cake" コマンドを利用できるようにします。`と出たので`dotnet tool restore`を実行、その後再度`dotnet cake`を実行 

**予想される動作**
ビルド成功

**スクリーンショット**
必要に応じて、問題を説明するためのスクリーンショットを追加してください。

**環境:**
- OS: macOS Big Sur
- Version: 11.4
- 機種名: MacBook Air (M1, 2020)
- RAM: 16GB
- CPU: Apple M1

**その他**

**Comment by Chipsnet** [comment]
beditor_win-x64となっていたのでそれが悪いのかと思い `dotnet cake --runtime=osx-x64`を実行してみたのですが、それでも結果は変わりませんでした

**Comment by yuto-trd** [comment]
一応 ビルドできるようにしたのですが、macOSを持ってないのでちゃんと動くかは分からないです。(0ec48d5381778d7dc2861e97cd90b2c153fb3b3b)

**Comment by Chipsnet** [comment]
ビルドはうまくいったみたいですが動きません		
Mac対応をきちんと確認していないのにHPにMac対応と書くのはどうなんでしょう・・・？

**Comment by yuto-trd** [comment]
動かないというのは、起動できないということですか？

**Comment by yuto-trd** [comment]
OSに依存する部分はライブラリを使っているので確認を怠っていました。
macOSで動作確認するまで "macOS対応" の文字を消しておきます。
