### ISSUE TITLE
イージングのグラフをGUIで表示する

### ISSUE THREAD

**Issue by indigo-san** [b-editor/BEditor#312]
## 概要
下のようなグラフを自動で生成してGUIから見れるようにする

![Screenshot_20210723_104912_com.microsoft.emmx_kindlephoto-129629634.jpg](https://user-images.githubusercontent.com/66758394/126728901-b64324ae-5c02-46ab-bd25-5376523323e5.jpg)

**Comment by yuto-trd** [comment]
b7d17408fa56563c1b8ad3051173143108bdc14e
