### ISSUE TITLE
GitHub ActionsでBuildした時に生成物をアップしてほしい

### ISSUE THREAD

**Issue by tomo0611** [b-editor/BEditor#316]
# 概要
* GitHub ActionsでBuildした時に生成物をアップしてほしい

# 詳細
今の所、ActionsでBuildしたあとはテストして終わりのようですが、せっかくビルドしているのですし、生成物をダウンロードできれば嬉しいのですが、可能でしょうか？

ワークフローが終わったら生成物をアップするようにするパッケージ(?)
https://github.com/actions/upload-artifact

プルリクを贈ろうと思いましたが、C#のmsbuildでどのようなディレクトリ構造になるか知らないので、issueとして立てさせていただきました。

↓自分のところではこんな感じに動いてます
![image](https://user-images.githubusercontent.com/31959526/126901052-7f853da8-4941-428e-937e-3bdbd084122c.png)

**Comment by yuto-trd** [comment]
今のワークフローで生成されるバイナリは
Debugビルドで .NET 5に依存していて、スタンドアローンで動かないですがそれでもいいですか？

**Comment by tomo0611** [comment]
スタンドアローンで動かなくても、(すでに.NET 5を入れてる)開発者には次期のメジャーアップデートのテストがしやすくなると思うので嬉しいかなと
可能ならお願いします

**Comment by yuto-trd** [comment]
分かりました
