### ISSUE TITLE
文字化けする

### ISSUE THREAD

**Issue by indigo-san** [b-editor/BEditor#326]
**バグの説明**
英語と日本語が混ざった文字が文字化けする

**スクリーンショット**
![20210728_180806_kindlephoto-428527910.png](https://user-images.githubusercontent.com/66758394/127296294-1acce117-eabb-4fed-833e-374b9e8c3b35.png)

**Comment by yuto-trd** [comment]
![スクリーンショット 2021-07-28 213513.png](https://user-images.githubusercontent.com/66758394/127340605-6b0c82df-b504-4678-b166-a62f102af6f8.png)

![Screenshot 2021-07-28 215802.png](https://user-images.githubusercontent.com/66758394/127340745-2636150f-465f-46ac-80be-bd81919d1527.png)

**Comment by nyanrus** [comment]
**再現**
再現するための手順:

  1. dotnet cakeでビルドする
  2. OpenALを削除する
  3. 再起動する(しなくてもいいかも)
  4. ビルドしたbeditor.exeを実行し、すぐに違うプログラムのタブを開く
  5. バグが再現されるまで4を繰り返す(5回以内でできると思います)

**環境:**
* OS: Windows10
* Version: 21H1
* Build: 19043.1110

バイトコードを出力させて見て、UTF8に直したら正常だったのでAvaloniaの方のバグだと思われます。

**Comment by nyanrus** [comment]
多分解決(OpenAL文字化け)
BEditor\src\executable\BEditor.Avalonia\Views\DialogContent\MessageContent.axamlの、
x:NameがlabelなものにFontFamilyを指定してください。
ProgressDialogも同じ方法でできると思います。

**Comment by nyanrus** [comment]
#344
