### ISSUE TITLE
"縁取り (テキスト)" をFormattedTextから適用できるようにする

### ISSUE THREAD

**Issue by indigo-san** [b-editor/BEditor#336]
## 概要
FormattedTextと `Image.StrokeText` の実装が違いすぎて、
FormattedTextで描画された文字に `Image.StrokeText` の縁をつけるとずれてしまうので、FormattedTextに縁取りの設定をできるようにする。

**Comment by yuto-trd** [comment]
de6207e67315a4771650d57902249f34fd09eb23
