### ISSUE TITLE
プロジェクト作成時に画像サイズ、fpsなどをプリセットで選べるようにしてほしい

### ISSUE THREAD

**Issue by indigo-san** [b-editor/BEditor#348]
## 概要
プロジェクト作成時にフルHD、4k、24fps、30fps、60fps等のちょっとしたプリセットを選択できるようにしてほしい

## その他
Discordのアイデアから作成

**Comment by yuto-trd** [comment]
8ead5ffd88f2a5dcfa3b605d9ec0954c8b7f458c
