### ISSUE TITLE
AudioFileの発する音に雑音が入る

### ISSUE THREAD

**Issue by GnicoJP** [b-editor/BEditor#378]
**バグの説明**
書き出しやプレビューで，AudioFileの発する音に雑音が入る．
AudioFile.OnSampleメソッドが書き込むバッファサイズが正しくないことが原因だと思われる．

**再現**
再現するための手順:
1. 30FPS，44.1kHzでプロジェクトを作成する．（3の倍数のFPSであれば，どんな設定でも発生するはず．）
2. AudioFileを追加する．
3. 適当な音声ファイルを鳴らすようにする．
4. 書き出したり，プレビュー再生したりする．
5. 発する音に雑音が入る．

**予想される動作**
正しく音声が出力される．

**環境:**
 - OS: Windows 11
 - Version: RTM Insider Preview
 - Build: 22000.160

**その他**
`AudioFile.OnSample`メソッドが書き込むバッファサイズが正しくないことが原因だと思われる．
`Sound<T>.Slice`メソッドに，次の行を加えてみる．
```csharp
System.Diagnostics.Debug.WriteLine("{0},{1}", (int)(start.TotalSeconds * SampleRate), (int)(length.TotalSeconds * SampleRate));
```
例えば，わかりやすさのためにプロジェクトを`AudioFile`だけにして，
連番で`OnSample`が呼ばれる動画の書き出しをしてみると，
次のように出力される．（30fps, 44.1kHz）
```
0,1469
1469,1469
2939,1469
4410,1469
5879,1469
...
```
1フレーム当たりに書き込まれるサンプル数が{1}のところに表示される．
30fpsで44.1kHzの場合，1フレーム当たり44.1k÷30=1470サンプル書き込まれなければならないが，1つ足りない．
また，ログ表示を見ると2938と4409は出力されていないことがわかる．

これは，`AudioFile.OnSample`メソッドで丸め誤差が起きていることが原因である．
`OnSample`メソッド内のローカル変数`start`や`length`の計算で1/30が行われるが，`TimeSpan`では丸められてしまう．
その結果，例えば最初のフレームの`length`の計算では，
```csharp
1470/30 = 0.00333333333333333
```
となるが，`TimeSpan.FromSeconds`により，Tickの桁までに丸められてしまう．
よって，`length.TotalSeconds = 0.0033333`となってしまう．
`Sound<T>.Slice(TimeSpan, TimeSpan)`内で，
```csharp
length.TotalSeconds * SampleRate =1469.9853
```
となってしまうので，intにキャストするときに，丸められてしまい，書き込むサイズが1469となってしまう．

その場しのぎの解決方法として，`AudioFile.OnSample`メソッドの戻り値を次のようにする．
```csharp
return Loaded.Slice((args.Frame - Parent.Start) * context.SamplePerFrame, context.SamplePerFrame);
```

あるいは，`TimeSpan`型ではなく，Rationalな時間を表す型を別に作り，丸め誤差が発生しないようにする．

**Comment by yuto-trd** [comment]
出力時の雑音は修正できましたが、再生時の雑音は未解決です。

**Comment by GnicoJP** [comment]
コミットを拝見させていただきましたが，`Math.Round`で対処するのはあまりよくないのかなと思いました．
時間からフレームレートや音声のサンプル数に変換するコードを書くときに，いちいち気を付けなければならないからです．
（再生時の雑音も，どこかで変換が失敗しているのかもしれません．）
差し支えなければ，`TimeSpan`型を使わずに，30fpsなどを正確に表現できる型を別に作って置き換えるプルリクを作って送りたいと思うのですが，いかがですか．
（まとまった時間が取れないので，いつ送れるかわかりませんが(;^_^A）

**Comment by yuto-trd** [comment]
分かりました
TimeSpanでは無くRational型を使うように変更しておきます

**Comment by yuto-trd** [comment]
一応、Rational型でやってみたのですが変わらなかったので。
プレビューに関係のあるコードを見直してみたら、マルチスレッドの排他制御ができていないのが原因でした
b65143add201c14ee429e6ba42047648dc17fdb9
