### ISSUE TITLE
プレビュー画面のレイアウトを変更

### ISSUE THREAD

**Issue by indigo-san** [b-editor/BEditor#404]
## 概要
プレビュー画面のレイアウトを変更して再生ボタンがシークバーの真下に来るようにして欲しい、また再生時間も青文字にして見やすく、総合計時間も見れるようにして欲しい 。フレーム数が1桁のときに10の位にゼロをつけてほしい。(フレーム番号のを前、`と送ってしまいましたが、'を使っていただけたら嬉しいです)

## その他
Discordのアイデアから作成

**Comment by yuto-trd** [comment]
![image](https://user-images.githubusercontent.com/66758394/137429272-7eca6dea-afb8-408b-9067-9dee78c9ca7b.png)
