### ISSUE TITLE
グラデーション効果で色を手打ち入力しなくてもいいようにして欲しい

### ISSUE THREAD

**Issue by indigo-san** [b-editor/BEditor#429]
## 概要
グラデーション効果で色を手打ち入力しなくてもいいようにして欲しい

## その他
Discordのアイデアから作成

**Comment by yuto-trd** [comment]
![image](https://user-images.githubusercontent.com/66758394/138065996-6a08fe4d-9ceb-478e-ae7b-36a1f1860293.png)
