### ISSUE TITLE
プラグインで対応言語を増やせるようにする

### ISSUE THREAD

**Issue by indigo-san** [b-editor/BEditor#434]
## 概要
プラグインで言語を増やせるようにする。

## Task
- [x] 10の文字列リソースを統合する
- [x] PluginBuilderから対応言語を登録できるようにする

**Comment by yuto-trd** [comment]
#437

**Comment by yuto-trd** [comment]
現在使われている言語がアンインストールするプラグインによって提供されている場合、
インストーラーの起動前に言語設定をデフォルトに変更する。
