### ISSUE TITLE
翻訳やリソース集約のために、言語リソースを統合する

### ISSUE THREAD

**Issue by nyanrus** [b-editor/BEditor#437]
## 問題

言語リソースが分散しているため、将来的な修正や翻訳が難しい

## 解決案
言語リソースを一つのフォルダ及び一つのnamespaceに統合し、
それをライブラリに参照させる。

- 良いところ
    全体的な管理が楽になる。
    同じ変数名(Key)で違う値(Value)を使うことを防止できる

- 悪いところ
    どんなライブラリがどんな変数(Key)を使っているか、すぐに把握できなくなる。
    特殊なとき、同じ変数名(Key)で違う値(Value)を使うことができなくなる。
    Baseが違うcsprojを参照するようになる

- 悪いところを解決する方法
    違うnamespaceを使う

## 参考資料
Resourceフォルダのあるところ

executable/BEditor.PackageInstaller

extensions/BEditor.Extensions.Aviutl
extensions/BEditor.Extensions.MotionTrack

libraries/BEditor.Audio
libraries/BEditor.Base
libraries/BEditor.Core
libraries/BEditor.Drawing
libraries/BEditor.Graphics
libraries/BEditor.Graphics.OpenGL
libraries/BEditor.Graphics.Veldrid
libraries/BEditor.Media
libraries/BEditor.Primitive

../test/DrawingTest

## 将来的に
プラグイン翻訳対応APIなどを作りたいと思っています。
プラグインAPIも、もうちょっとわかりやすく作りたいです。

## (私が)すること
- [x] Resourceフォルダ作って、
- [x] Resource使うライブラリに参照させて、
- [x] pull-request投げる

**Comment by nyanrus** [comment]
namespace統合はしんどすぎるので、各自Designer.csを結合することで一時的に対処する。
統合はLangResource namespace及びフォルダにする予定

**Comment by nyanrus** [comment]
あと試験期間なので、本格的な統合は再来週になるかもしれません。
結合までは先にしておきます。

**Comment by nyanrus** [comment]
![image](https://user-images.githubusercontent.com/68762426/138680254-9972850a-2713-4462-8b9a-268ca432f5c9.png)

**Comment by nyanrus** [comment]
@indigo-san executableとlibrariesのResourceは統合するのでしょうか。
主にexecutable/Avalonia/Propertiesとlibraries/BEditor.~~/Resourcesの間で同じKey名で違うValueを使っているみたいなので
https://gist.github.com/touyu7720/b650983b52bbd7146ce3a8d8273ab39f
^自作統合プログラムのログです

**Comment by yuto-trd** [comment]
同じKey名で違うValueの場合、手動でKeyを変更したいので統合しないでほしいです。

**Comment by nyanrus** [comment]
libraries内で違うValueのKeyはないようなので、一旦libraries内での統合にしておきます。

**Comment by yuto-trd** [comment]
分かりました

**Comment by nyanrus** [comment]
![image](https://user-images.githubusercontent.com/68762426/138893041-993dd692-cf54-40cf-9afe-7347263091b0.png)
うわあああああああああああああああああああああ

**Comment by nyanrus** [comment]
![image](https://user-images.githubusercontent.com/68762426/139011751-db1e2935-35df-4fed-8422-aed5c9782220.png)
!!!!!!

**Comment by nyanrus** [comment]
![image](https://user-images.githubusercontent.com/68762426/139011870-d9e3df5c-2657-4b4d-86f3-7f61a9ce0d6b.png)
これは完成っしょ
