### ISSUE TITLE
AviUtl Exedit Interop

### ISSUE THREAD

**Issue by indigo-san** [b-editor/BEditor#44]
## AviUtl Exedit Interop

KENくん氏のソフトウェアAviUtlとExeditとの相互運用のために以下の機能を持つ拡張機能を作る  

* exoファイルの入出力
* エイリアスファイルの入出力
* luaスクリプリティング(対応出来ないapiは無視)

[開発リポジトリ](https://github.com/indigo-san/BEditor.Extension.AviUtl)

**Comment by yuto-trd** [comment]
https://github.com/b-editor/BEditor.Extension.AviUtl

で開発中
