### ISSUE TITLE
resxファイルから.Designer.csを生成するソースジェネレーターを作る

### ISSUE THREAD

**Issue by indigo-san** [b-editor/BEditor#451]
## 概要
プラグインで言語を拡張できるようになったが、
存在しないリソースを取得しようとすると例外が投げられるので
その対策ができるように.Designer.csファイルのジェネレーターを実装する

**Comment by nyanrus** [comment]
Windows SDKに入ってるresgen.exeを使えばいいと思います。
ちなみにリソースを統合するときには 
`/str:cs,BEditor.LangResource,Strings,Strings.Designer.cs /publicclass`
オプションを使っていたはずです

参考
https://docs.microsoft.com/ja-jp/dotnet/framework/tools/resgen-exe-resource-file-generator
