### ISSUE TITLE
エフェクトの追加

### ISSUE THREAD

**Issue by indigo-san** [b-editor/BEditor#47]
画像エフェクトを追加します

## 追加するエフェクト
* [x] [クロマキー](https://stackoverflow.com/questions/20901093/c-sharp-net-green-screen-background-remove)
* [x] マスク
* [x] [線状グラデーション](https://docs.microsoft.com/ja-jp/xamarin/xamarin-forms/user-interface/graphics/skiasharp/effects/shaders/linear-gradient)
* [x] [円形グラデーション](https://docs.microsoft.com/ja-jp/xamarin/xamarin-forms/user-interface/graphics/skiasharp/effects/shaders/circular-gradients) 
* [x] [エンボス](https://docs.microsoft.com/ja-jp/xamarin/xamarin-forms/user-interface/graphics/skiasharp/effects/image-filters)

## 使用するライブラリ
* Skiasharp

**Comment by yuto-trd** [comment]
次のバージョンに引き継ぎ
