### ISSUE TITLE
BEditorでプロジェクトファイルを新規作成・読み込むとクラッシュする。

### ISSUE THREAD

**Issue by YiB-PC** [b-editor/BEditor#72]
**問題の再現**
再現方法（？）:
1. プロジェクトファイルを新規作成します。
2. 一瞬編集画面（タイムライン？）が表示されてから、「BEditor.Graphics.GraphicsException」がスローされてクラッシュ
または：
1. すでに作成されたプロジェクトファイルを開く
2. すぐにフリーズしてクラッシュする

**スクリーンショット**
プロジェクトファイル新規作成時に一瞬表示されるエラー
![クラッシュ前に一瞬表示されるエラー](https://pbs.twimg.com/media/Eu4N27zVkAA65PE?format=png&name=small)

**PC :**
 - OS: Windows10 Pro InsiderPreview Build: 21313.1000(64Bit);
 - CPU: Ryzen3 3100;
 - Ram: DDR4-3200 16GB;
 - GPU: Geforce GTX1650;

**その他**
スタートウィンドウを表示しない設定にして編集画面から新規プロジェクトを作成しても同じ挙動になる。

**Comment by yuto-trd** [comment]
GraphicsExceptionは主にシェーダーにコンパイルに呼ばれるので、GPUのドライバなどを確認して欲しいです

**Comment by ghost** [comment]
GPUのドライバを再インストールしてみたんですが、やっぱりクラッシュしてしまいます。

**Comment by ghost** [comment]
{ "time": "2021-02-23 11:39:08.8966", "level": "ERROR", "type": "BEditor.Graphics.GraphicsException", "exception": "Shader(2) \u306e\u30b3\u30f3\u30d1\u30a4\u30eb\u4e2d\u306b\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\\n\\n0(8) : error C1105: cannot call a non-function\n*BEditor.Graphics.GraphicsException: Shader(2) \u306e\u30b3\u30f3\u30d1\u30a4\u30eb\u4e2d\u306b\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\\n\\n0(8) : error C1105: cannot call a non-function\n\r\n   at BEditor.Graphics.Shader.CompileShader(Int32 shader) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\Shader.cs:line 83\r\n   at BEditor.Graphics.Shader..ctor(String vertSource, String fragSource) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\Shader.cs:line 34\r\n   at BEditor.Graphics.GraphicsContext..ctor(Int32 width, Int32 height) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\GraphicsContext.cs:line 60\r\n   at BEditor.Data.Scene.<OnLoad>b__97_0(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 358\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)", "message": "UnhandledException was thrown.", "innerException": { "time": "2021-02-23 11:39:08.8966", "level": "ERROR" } }
{ "time": "2021-02-23 11:39:08.9498", "level": "ERROR", "type": "System.NullReferenceException", "exception": "Object reference not set to an instance of an object.*System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at BEditor.Data.Scene.Render(Image`1 image, Frame frame, RenderType renderType) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 441\r\n   at BEditor.Data.Scene.Render(Image`1 image, RenderType renderType) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 465\r\n   at BEditor.Data.Project.<Save>b__47_1(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Project.cs:line 230\r\n   at BEditor.Data.Project.<Save>b__47_1(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Project.cs:line 232\r\n   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)", "message": "UnhandledException was thrown.", "innerException": { "time": "2021-02-23 11:39:08.9498", "level": "ERROR" } }
{ "time": "2021-02-23 11:39:43.3725", "level": "ERROR", "type": "BEditor.Graphics.GraphicsException", "exception": "Shader(2) \u306e\u30b3\u30f3\u30d1\u30a4\u30eb\u4e2d\u306b\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\\n\\n0(8) : error C1105: cannot call a non-function\n*BEditor.Graphics.GraphicsException: Shader(2) \u306e\u30b3\u30f3\u30d1\u30a4\u30eb\u4e2d\u306b\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\\n\\n0(8) : error C1105: cannot call a non-function\n\r\n   at BEditor.Graphics.Shader.CompileShader(Int32 shader) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\Shader.cs:line 83\r\n   at BEditor.Graphics.Shader..ctor(String vertSource, String fragSource) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\Shader.cs:line 34\r\n   at BEditor.Graphics.GraphicsContext..ctor(Int32 width, Int32 height) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\GraphicsContext.cs:line 60\r\n   at BEditor.Data.Scene.<OnLoad>b__97_0(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 358\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)", "message": "UnhandledException was thrown.", "innerException": { "time": "2021-02-23 11:39:43.3725", "level": "ERROR" } }
{ "time": "2021-02-23 11:40:12.3053", "level": "ERROR", "type": "BEditor.Graphics.GraphicsException", "exception": "Shader(2) \u306e\u30b3\u30f3\u30d1\u30a4\u30eb\u4e2d\u306b\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\\n\\n0(8) : error C1105: cannot call a non-function\n*BEditor.Graphics.GraphicsException: Shader(2) \u306e\u30b3\u30f3\u30d1\u30a4\u30eb\u4e2d\u306b\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\\n\\n0(8) : error C1105: cannot call a non-function\n\r\n   at BEditor.Graphics.Shader.CompileShader(Int32 shader) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\Shader.cs:line 83\r\n   at BEditor.Graphics.Shader..ctor(String vertSource, String fragSource) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\Shader.cs:line 34\r\n   at BEditor.Graphics.GraphicsContext..ctor(Int32 width, Int32 height) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\GraphicsContext.cs:line 60\r\n   at BEditor.Data.Scene.<OnLoad>b__97_0(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 358\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)", "message": "UnhandledException was thrown.", "innerException": { "time": "2021-02-23 11:40:12.3053", "level": "ERROR" } }
{ "time": "2021-02-23 11:40:12.3432", "level": "ERROR", "type": "System.NullReferenceException", "exception": "Object reference not set to an instance of an object.*System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at BEditor.Data.Scene.Render(Image`1 image, Frame frame, RenderType renderType) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 441\r\n   at BEditor.Data.Scene.Render(Image`1 image, RenderType renderType) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 465\r\n   at BEditor.Data.Project.<Save>b__47_1(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Project.cs:line 230\r\n   at BEditor.Data.Project.<Save>b__47_1(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Project.cs:line 232\r\n   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)", "message": "UnhandledException was thrown.", "innerException": { "time": "2021-02-23 11:40:12.3432", "level": "ERROR" } }
{ "time": "2021-02-23 11:40:59.9900", "level": "ERROR", "type": "BEditor.Graphics.GraphicsException", "exception": "Shader(2) \u306e\u30b3\u30f3\u30d1\u30a4\u30eb\u4e2d\u306b\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\\n\\n0(8) : error C1105: cannot call a non-function\n*BEditor.Graphics.GraphicsException: Shader(2) \u306e\u30b3\u30f3\u30d1\u30a4\u30eb\u4e2d\u306b\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\\n\\n0(8) : error C1105: cannot call a non-function\n\r\n   at BEditor.Graphics.Shader.CompileShader(Int32 shader) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\Shader.cs:line 83\r\n   at BEditor.Graphics.Shader..ctor(String vertSource, String fragSource) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\Shader.cs:line 34\r\n   at BEditor.Graphics.GraphicsContext..ctor(Int32 width, Int32 height) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\GraphicsContext.cs:line 60\r\n   at BEditor.Data.Scene.<OnLoad>b__97_0(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 358\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)", "message": "UnhandledException was thrown.", "innerException": { "time": "2021-02-23 11:40:59.9900", "level": "ERROR" } }
{ "time": "2021-02-23 11:41:42.2832", "level": "ERROR", "type": "BEditor.Graphics.GraphicsException", "exception": "Shader(2) \u306e\u30b3\u30f3\u30d1\u30a4\u30eb\u4e2d\u306b\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\\n\\n0(8) : error C1105: cannot call a non-function\n*BEditor.Graphics.GraphicsException: Shader(2) \u306e\u30b3\u30f3\u30d1\u30a4\u30eb\u4e2d\u306b\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\\n\\n0(8) : error C1105: cannot call a non-function\n\r\n   at BEditor.Graphics.Shader.CompileShader(Int32 shader) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\Shader.cs:line 83\r\n   at BEditor.Graphics.Shader..ctor(String vertSource, String fragSource) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\Shader.cs:line 34\r\n   at BEditor.Graphics.GraphicsContext..ctor(Int32 width, Int32 height) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\GraphicsContext.cs:line 60\r\n   at BEditor.Data.Scene.<OnLoad>b__97_0(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 358\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)", "message": "UnhandledException was thrown.", "innerException": { "time": "2021-02-23 11:41:42.2832", "level": "ERROR" } }
{ "time": "2021-02-23 11:41:42.3222", "level": "ERROR", "type": "System.NullReferenceException", "exception": "Object reference not set to an instance of an object.*System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at BEditor.Data.Scene.Render(Image`1 image, Frame frame, RenderType renderType) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 441\r\n   at BEditor.Data.Scene.Render(Image`1 image, RenderType renderType) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 465\r\n   at BEditor.Data.Project.<Save>b__47_1(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Project.cs:line 230\r\n   at BEditor.Data.Project.<Save>b__47_1(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Project.cs:line 232\r\n   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)", "message": "UnhandledException was thrown.", "innerException": { "time": "2021-02-23 11:41:42.3222", "level": "ERROR" } }
{ "time": "2021-02-23 11:41:50.7461", "level": "ERROR", "type": "BEditor.Graphics.GraphicsException", "exception": "Shader(2) \u306e\u30b3\u30f3\u30d1\u30a4\u30eb\u4e2d\u306b\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\\n\\n0(8) : error C1105: cannot call a non-function\n*BEditor.Graphics.GraphicsException: Shader(2) \u306e\u30b3\u30f3\u30d1\u30a4\u30eb\u4e2d\u306b\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\\n\\n0(8) : error C1105: cannot call a non-function\n\r\n   at BEditor.Graphics.Shader.CompileShader(Int32 shader) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\Shader.cs:line 83\r\n   at BEditor.Graphics.Shader..ctor(String vertSource, String fragSource) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\Shader.cs:line 34\r\n   at BEditor.Graphics.GraphicsContext..ctor(Int32 width, Int32 height) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\GraphicsContext.cs:line 60\r\n   at BEditor.Data.Scene.<OnLoad>b__97_0(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 358\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)", "message": "UnhandledException was thrown.", "innerException": { "time": "2021-02-23 11:41:50.7461", "level": "ERROR" } }
{ "time": "2021-02-23 11:42:03.5417", "level": "ERROR", "type": "BEditor.Graphics.GraphicsException", "exception": "Shader(2) \u306e\u30b3\u30f3\u30d1\u30a4\u30eb\u4e2d\u306b\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\\n\\n0(8) : error C1105: cannot call a non-function\n*BEditor.Graphics.GraphicsException: Shader(2) \u306e\u30b3\u30f3\u30d1\u30a4\u30eb\u4e2d\u306b\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\\n\\n0(8) : error C1105: cannot call a non-function\n\r\n   at BEditor.Graphics.Shader.CompileShader(Int32 shader) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\Shader.cs:line 83\r\n   at BEditor.Graphics.Shader..ctor(String vertSource, String fragSource) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\Shader.cs:line 34\r\n   at BEditor.Graphics.GraphicsContext..ctor(Int32 width, Int32 height) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\GraphicsContext.cs:line 60\r\n   at BEditor.Data.Scene.<OnLoad>b__97_0(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 358\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)", "message": "UnhandledException was thrown.", "innerException": { "time": "2021-02-23 11:42:03.5417", "level": "ERROR" } }
{ "time": "2021-02-23 11:42:03.5785", "level": "ERROR", "type": "System.NullReferenceException", "exception": "Object reference not set to an instance of an object.*System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at BEditor.Data.Scene.Render(Image`1 image, Frame frame, RenderType renderType) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 441\r\n   at BEditor.Data.Scene.Render(Image`1 image, RenderType renderType) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 465\r\n   at BEditor.Data.Project.<Save>b__47_1(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Project.cs:line 230\r\n   at BEditor.Data.Project.<Save>b__47_1(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Project.cs:line 232\r\n   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)", "message": "UnhandledException was thrown.", "innerException": { "time": "2021-02-23 11:42:03.5785", "level": "ERROR" } }
{ "time": "2021-02-23 11:42:25.1445", "level": "ERROR", "type": "BEditor.Graphics.GraphicsException", "exception": "Shader(2) \u306e\u30b3\u30f3\u30d1\u30a4\u30eb\u4e2d\u306b\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\\n\\n0(8) : error C1105: cannot call a non-function\n*BEditor.Graphics.GraphicsException: Shader(2) \u306e\u30b3\u30f3\u30d1\u30a4\u30eb\u4e2d\u306b\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\\n\\n0(8) : error C1105: cannot call a non-function\n\r\n   at BEditor.Graphics.Shader.CompileShader(Int32 shader) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\Shader.cs:line 83\r\n   at BEditor.Graphics.Shader..ctor(String vertSource, String fragSource) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\Shader.cs:line 34\r\n   at BEditor.Graphics.GraphicsContext..ctor(Int32 width, Int32 height) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\GraphicsContext.cs:line 60\r\n   at BEditor.Data.Scene.<OnLoad>b__97_0(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 358\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)", "message": "UnhandledException was thrown.", "innerException": { "time": "2021-02-23 11:42:25.1445", "level": "ERROR" } }
{ "time": "2021-02-23 11:42:25.1815", "level": "ERROR", "type": "System.NullReferenceException", "exception": "Object reference not set to an instance of an object.*System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at BEditor.Data.Scene.Render(Image`1 image, Frame frame, RenderType renderType) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 441\r\n   at BEditor.Data.Scene.Render(Image`1 image, RenderType renderType) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 465\r\n   at BEditor.Data.Project.<Save>b__47_1(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Project.cs:line 230\r\n   at BEditor.Data.Project.<Save>b__47_1(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Project.cs:line 232\r\n   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)", "message": "UnhandledException was thrown.", "innerException": { "time": "2021-02-23 11:42:25.1815", "level": "ERROR" } }
{ "time": "2021-02-23 12:04:35.0029", "level": "ERROR", "type": "BEditor.Graphics.GraphicsException", "exception": "Shader(2) \u306e\u30b3\u30f3\u30d1\u30a4\u30eb\u4e2d\u306b\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\\n\\n0(8) : error C1105: cannot call a non-function\n*BEditor.Graphics.GraphicsException: Shader(2) \u306e\u30b3\u30f3\u30d1\u30a4\u30eb\u4e2d\u306b\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\\n\\n0(8) : error C1105: cannot call a non-function\n\r\n   at BEditor.Graphics.Shader.CompileShader(Int32 shader) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\Shader.cs:line 83\r\n   at BEditor.Graphics.Shader..ctor(String vertSource, String fragSource) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\Shader.cs:line 34\r\n   at BEditor.Graphics.GraphicsContext..ctor(Int32 width, Int32 height) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\GraphicsContext.cs:line 60\r\n   at BEditor.Data.Scene.<OnLoad>b__97_0(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 358\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)", "message": "UnhandledException was thrown.", "innerException": { "time": "2021-02-23 12:04:35.0029", "level": "ERROR" } }
{ "time": "2021-02-23 12:04:35.0954", "level": "ERROR", "type": "System.NullReferenceException", "exception": "Object reference not set to an instance of an object.*System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at BEditor.Data.Scene.Render(Image`1 image, Frame frame, RenderType renderType) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 441\r\n   at BEditor.Data.Scene.Render(Image`1 image, RenderType renderType) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 465\r\n   at BEditor.Data.Project.<Save>b__47_1(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Project.cs:line 230\r\n   at BEditor.Data.Project.<Save>b__47_1(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Project.cs:line 232\r\n   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)", "message": "UnhandledException was thrown.", "innerException": { "time": "2021-02-23 12:04:35.0954", "level": "ERROR" } }
{ "time": "2021-02-23 12:32:13.5095", "level": "ERROR", "type": "BEditor.Graphics.GraphicsException", "exception": "Shader(2) \u306e\u30b3\u30f3\u30d1\u30a4\u30eb\u4e2d\u306b\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\\n\\n0(8) : error C1105: cannot call a non-function\n*BEditor.Graphics.GraphicsException: Shader(2) \u306e\u30b3\u30f3\u30d1\u30a4\u30eb\u4e2d\u306b\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\\n\\n0(8) : error C1105: cannot call a non-function\n\r\n   at BEditor.Graphics.Shader.CompileShader(Int32 shader) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\Shader.cs:line 83\r\n   at BEditor.Graphics.Shader..ctor(String vertSource, String fragSource) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\Shader.cs:line 34\r\n   at BEditor.Graphics.GraphicsContext..ctor(Int32 width, Int32 height) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\GraphicsContext.cs:line 60\r\n   at BEditor.Data.Scene.<OnLoad>b__97_0(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 358\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)", "message": "UnhandledException was thrown.", "innerException": { "time": "2021-02-23 12:32:13.5095", "level": "ERROR" } }
{ "time": "2021-02-23 12:38:42.0396", "level": "ERROR", "type": "BEditor.Graphics.GraphicsException", "exception": "Shader(2) \u306e\u30b3\u30f3\u30d1\u30a4\u30eb\u4e2d\u306b\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\\n\\n0(8) : error C1105: cannot call a non-function\n*BEditor.Graphics.GraphicsException: Shader(2) \u306e\u30b3\u30f3\u30d1\u30a4\u30eb\u4e2d\u306b\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\\n\\n0(8) : error C1105: cannot call a non-function\n\r\n   at BEditor.Graphics.Shader.CompileShader(Int32 shader) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\Shader.cs:line 83\r\n   at BEditor.Graphics.Shader..ctor(String vertSource, String fragSource) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\Shader.cs:line 34\r\n   at BEditor.Graphics.GraphicsContext..ctor(Int32 width, Int32 height) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Graphics\\GraphicsContext.cs:line 60\r\n   at BEditor.Data.Scene.<OnLoad>b__97_0(Object _) in E:\\yuuto\\source\\BEditor.Org\\BEditor\\src\\BEditor.Core\\Data\\Scene.cs:line 358\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)", "message": "UnhandledException was thrown.", "innerException": { "time": "2021-02-23 12:38:42.0396", "level": "ERROR" } }

Logです。
