### ISSUE TITLE
#32 スクリプトで編集

### ISSUE THREAD

**Issue by indigo-san** [b-editor/BEditor#74]
CLIツールの `bedit open` で編集する時、replっぽくする

### メモ
* C#スクリプトを使う
* セミコロンなし
* メソッド
    * Save([file])
    * List(clips or scenes or effects)
    * Prop(path)
    * Add(range, layer, type[, setcurrent = false])
    * Add(type)
    * Add(width, height, background)
    * Remove(clip)
    * Remove(effect)
    * Move(layer)
    * Move(range)
    * HideLayer(layer)
    * ShowFrame()
    * Undo([count = 1])
    * Redo([count = 1])
    * Encode(file)
    * EncodeImg(file, frame)
* プロパティ
    * Directory get
    * Name get
    * Samplingrate get
    * Framerate get
    * Scene
    * Scenes
    * Clip
    * Clips

**Comment by yuto-trd** [comment]
8685d943dbf554a5a15401f11ec74a365f75f9cf のコミットで実装
